### ISSUE TITLE
WARNING: No conversion needed for file

### ISSUE THREAD

**Issue by casz** [budius/ChromecastConverter#5]
Does it really need to be a warning?

**Comment by budius** [comment]
@casz that's an interesting point. On this ticket here https://github.com/budius/ChromecastConverter/issues/3 I'm planning to have a `-m` option to move original files to output folder when output folder is specified.

The warning is important if you're converting a whole batch of videos with output in a different folder. Because when you're converting a whole batch, you really expect the output have everything done.

So my point is, maybe it should not be a warning in all situations, but only in very specific situation.

What do you think of this `-m` flag? I'm thinking in doing it as default behavior instead of an extra flag?

**Comment by casz** [comment]
Can't see any reason for -m cause if it does not need conversion it should just move the file and instead of a warning just echo/log: moved file conversion not needed.

My use case is point it at NAS and make it go to town. Sadly it gets stuck on subtitle extraction sometimes.

Which is another issue.

I would like for the script to move/rename the old log files before overwriting them.
Of course I could make it automated but it would be a nice behavior

But if it could keep the folder structure somewhat it would be nice.

For instance: X:/TBC/House Wife/Season 1/episode 1.mkv
where -i is X:/TBC/
and -o Y:/TV shows/
But it would end up Y:/TV shows/House Wife/Season 1/episode 1.mp4
I haven't checked if it already does this cause I have always just chosen a input folder and made it go to town.

**Comment by budius** [comment]
@casz after my last message to you I already coded to not have that flag, it just moves the file. I agree it makes more sense.

Regarding the conversion of whole folders, check again the readme, it totally does it and this software is meant for that. On the version 1.0 of that thing I pointed to a 2 terabyte drive `/series/` and converted everything in one go keeping all the folder structures.

I'll check it out the logs, I thought it was appending new logs on top of the old ones, and not overwriting them.

I would suggest against using it in a NAS, because it certainly will take much longer, if possible to disconnect the drive from the NAS and bring over the PC, it should go quite faster.

Is it possible for you to share on dropbox or similar an example video that subtitle extraction gets stuck? I've never had this issue.

**Comment by casz** [comment]
I'll see if it hits the subtitle issue again and let you know.

It seems fast enough on NAS, running 5.5x on video copy and aac codec, I retry same file on hard drive and SSD.

**Comment by budius** [comment]
@casz just an update. I'm back on my 9-5 job and have little time to work on this.
But most of the code is written and I need to find some time on the weekend to proper test and release it.

**Comment by budius** [comment]
@casz there you go.
I found some spare time, the new version is up for grabs
